### PR TITLE
prevent `pages-deploy` GH action from running on forks by default

### PR DESCRIPTION
**Pull request by developomp**

### CODE REVIEW

**Comment by Puyodead1** [comment]
forks have to specifically enable actions anyways

**Comment by developomp** [comment]
> forks have to specifically enable actions anyways

They are enabled by default for me.

**Comment by TheArcaneBrony** [comment]
Wouldn't these deploy to temporary deployments anyways? What's the point of disabling these, as they allow previews of changes?

**Comment by Puyodead1** [comment]
> > forks have to specifically enable actions anyways
> 
> They are enabled by default for me.

I just created a fork, and I don't see an option in the user settings to disable this. 
image

**Comment by developomp** [comment]
Just checked again and you are right. Apparently forks show github action results from upstream.

image

**Pull request closed without merging**
